apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pod
  labels:
    app: my-app
    name: app-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      name: app-pod 
  template:
    metadata:
      name: app-pod
      labels:
        app: my-app
        name: app-pod
    spec:
      containers:
      - name: my-app
        image: docker pull gcr.io/rock-extension-337315/python:latest
        ports:
        - containerPort: 8000
        env:
          - name: ENVIRONMENT
            value: "DEV"
          - name: HOST
            value: "localhost"
          - name: PORT
            value: "8000"
          - name: REDIS_HOST
            value: "redis-ip-service"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"