apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  selector:
     app: my-app
     name: app-pod