apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  labels:
    app: my-app
    name: redis-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      name: redis-pod 
  template:
    metadata:
      name: redis-pod
      labels:
        app: my-app
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: gcr.io/rock-extension-337315/redis:latest
          ports:
            - containerPort: 6379